# Generated by Django 4.0.4 on 2022-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('sueldo', models.IntegerField()),
                ('comision', models.IntegerField()),
                ('acargo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presupuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie', models.FloatField()),
                ('tipo_trabajo', models.CharField(choices=[('Cerramientos', 'Cerramientos'), ('Piletas', 'Piletas'), ('Quinchos', 'Quinchos'), ('Techos', 'Techos')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajosHechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('cobrado', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
