# Generated by Django 4.0.4 on 2022-05-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Altec', '0002_presupuestos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='comision',
            field=models.FloatField(),
        ),
    ]
